apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-integration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8-integration
  template:
    metadata:
      labels:
        app: k8-integration
    spec:
      containers:
        - name: k8-integration
          image: mahmud255/k8-integration:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: k8-integration
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: k8-integration
